### PR TITLE
Start using zoapp-front + fixes

### PR DESCRIPTION
**Pull request by willdurand**
This PR needs:

- https://github.com/Zoapp/front/pull/15
- ~https://github.com/Zoapp/react-materialcomponents/pull/30~

### CODE REVIEW

**Comment by willdurand** [comment]
ah thanks!

**Comment by willdurand** [comment]
> DialogManager is deprecated. See how it works in zoapp/front. So you don't have to init it with store.

Isnt it `DialogManager` in zoapp/ui that is deprecated? I guess `DialogManager` in zoapp/front is still used/useful.

**Comment by mikbry** [comment]
don't use DialogManager but Rmdc.showDialog / Rmdc.closeDialog instead

**Comment by willdurand** [comment]
> don't use DialogManager but Rmdc.showDialog / Rmdc.closeDialog instead

oki!

**Comment by mikbry** [comment]
Why not using zoapp/front UserBox and Sign in/out Dialogs ?

**Comment by willdurand** [comment]
> Why not using zoapp/front UserBox and Sign in/out Dialogs ?

that would make sense I guess.

**Comment by willdurand** [comment]
Ok so I changed my mind and decided not to update the dialogs right now. There are too many and I am not sure how to fix all of them, lack of tests does not help unfortunately :(

**Comment by mikbry** [comment]
Ok I understand. I will work on it this week.

**Pull request merged**
