### PR TITLE
[WIP] Start using react-material-cw

### PR DESCRIPTION
**Pull request by willdurand**

### CODE REVIEW

**Comment by mikbry** [comment]
Maybe instead of rewriting directly from react-material-cw you should instead use zoapp/front as the starting point

**Comment by willdurand** [comment]
> Maybe instead of rewriting directly from react-material-cw you should instead use zoapp/front as the starting point

All `shared/*` files should be available in zoapp/front, right? If so, then I guess yes I can start by updating zoapp/front and then use zoapp/front here.

**Comment by mikbry** [comment]
Not all /shared/* files. I already put in zoapp/front all files that I think need to be in.

**Comment by willdurand** [comment]
> Not all /shared/* files. I already put in zoapp/front all files that I think need to be in.

Ok, then let's see if I can get rid of react-mdl in zoapp/front first, thanks.

**Pull request closed without merging**
