### PR TITLE
Add condition button

### LINKED ISSUE #89: ActionsToolbox : add condition button
## Where
screen shot 2018-04-23 at 22 57 29
Using icon name="device_hub"

## Behaviour
Add a condition to a new output
Transform a text output to a condition
See #88

### PR DESCRIPTION
**Pull request by lodelestra**
- [x] add condition button
- [x] add tests
close #89

### CODE REVIEW

**Comment by lodelestra** [comment]
The requested change is done

**Comment by mikbry** [comment]
Got this time to time:
screen shot 2018-06-11 at 16 51 07

**Comment by lodelestra** [comment]
It is the Zoapp/react-materialcomponents#119 issue about TextField

**Comment by mikbry** [comment]
Not sure

**Pull request merged**
