### PR TITLE
remove code duplicated from zoapp-front

### PR DESCRIPTION
**Pull request by lunika**
This PR remove code duplicated from zoapp-front and uses the original code.

### CODE REVIEW

**Comment by lunika** [comment]
@mikbry `appSetTitle` is already in `zoapp-front` and used from `zoapp-front` there is no modification to do with this actions IMO

**Comment by mikbry** [comment]
but why import from opla-front actions ?
`import { appSetTitle } from "../actions/app";`

**Comment by lunika** [comment]
in `actions/app` `appSetTitle` is imported from `zoapp-front` and then exported. So it is used fron `zoapp-front`

**Comment by mikbry** [comment]
Yep andI think we should use it directly, remove this unecessary step ?

**Comment by lunika** [comment]
ok I do it

**Pull request merged**
